### PR TITLE
Prepare for big merge

### PR DESCRIPTION
**Pull request by evoactivity**
Preparing for the big merge as discussed in #385

I've removed everything except the LICENSE.md so we don't remove original authors coyright. 
@lifeart can you solve the conflict by adding yourself to the list when creating your PR

### CODE REVIEW

**Comment by evoactivity** [comment]
Before I click the button does anyone see any issues with doing this?

@nullvoxpopuli @matchy @locks

**Comment by lifeart** [comment]
@evoactivity yep

**Review by lifeart — APPROVED** [review]

**Comment by evoactivity** [comment]
I've created an ember-tooling organisation on npm, I've invited @nullvoxpopuli and @lifeart to that organisation.

@lifeart we'll need to update the workflow so it publishes to that npm organisation

If there are others who should have access let me know.

**Comment by evoactivity** [comment]
@lifeart is there a reason this https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/.github/workflows/ci.yml#L131 doesn't use the standard `secret.GITHUB_TOKEN` ?

**Comment by lifeart** [comment]
@evoactivity I think it's legacy from https://github.com/lifeart/ember-language-server/commit/81728b6b77e9dc005e4e5253fb24e6eb1ac2bc22

**Comment by locks** [comment]
> Before I click the button does anyone see any issues with doing this?
> 
> 
> 
> @nullvoxpopuli @matchy @locks 

you're the boss!

**Comment by NullVoxPopuli** [comment]
image

if only every PR could be like this :sweat_smile:

**Pull request merged**
